name: Uffizzi Cluster Quickstart

on:
  pull_request:
    types: [opened,reopened,synchronize,closed]

permissions:
  id-token: write

jobs:
  oof-take-it-easy:
    name: testing ucluster creation via action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cluster-create
        id: cluster-create
        uses: UffizziCloud/cluster-action@main
        with:
          server: https://pr-1100-deployment-29999-uffizzi-platform.app.uffizzi.com/ 
          username: admin@uffizzi.com
          password: ${{ secrets.uffizzi_password }}
          project: default
          cluster-name: pr-${{ github.event.repository.name }}-${{ github.event.number }}
          image: uffizzi/cli:pr-239

      - name: apply kube manifests
        run: |
          kubectl apply -f manifests/ --kubeconfig kubeconfig
